let headers = ['OrganisationName',
  'schemename',
  'populationserved',
  'volumesupplied',
  'yearofreturn',
  'parameterdescription',
  'sampleid',
  'sampledate',
  'MonitoredLocationCode',
  'numericresult',
  'textresult',
  'schemecode',
  'supplytypecode',
  'Organisation Name',
  'Scheme Code',
  'Scheme Name',
  'Supply Type',
  'Sample ID',
  'Sample Date',
  'Parameter ',
  'Result',
  'Units',
  'Parametric Value',
  'Sanitary Authority',
  'Scheme Name/Water Supply',
  'Public/Private/Group',
  'Location',
  'Population Served',
  'Volume Supplied',
  'Year of Return',
  'Parameter',
  'Sample Type Category',
  'Parameter Description',
  'Actual Samples',
  'RequiredSamples',
  'Shortfall',
  'SupplyType',
  'SchemeCode',
  'SchemeName',
  'SourceType',
  'Source of Supply',
  'PopulationServed',
  'VolumeSupplied',
  'DerogationForSupply',
  'TypeOfTreatment',
  'SupplementaryInformation',
  'Does the plant have turbidity monitors after each filter \(if applicable\)\?',
  'Does the treatment plant have a chlorine residual monitor\?',
  'Does the treatment plant have a chlorine residual alarm\?',
  'Does the treatment plant have duty/assist chlorine/UV dosing\?',
  'Chlorine dosing is flow proportional/residual based\?',
  'Contact Time Calculation Complete',
  'Effective Contact Time \(CT\) mg\.min/l',
  'Crypto Catchment Score',
  'Crypto Treatment Score',
  'Overall Crypto Risk Screening Score',
  'Actions',
  'Version',
  'Comment',
  'Water Safety Plan \(WSP\) in place\?',
  'Water Safety Plan \(WSP\) preparation has commenced\?',
  'Drinking Water Incident Response Plan \(DWIRP\) in place\?',
  'SchemeStartDate',
  'SchemeEndDate',
  'LastUpdatedOn',
  'LastUpdatedBy',
  'No\. of WSZ Monitored',
  'No of WSZ with Non-Compliances',
  '% of WSZs complying',
  'No\. of Samples Analysed',
  'No\. of Non-Compliant Samples',
  '% of Samples complying',
  'Location ',
  'Volume Supplies',
  'Required Samples',
  'Short fall',
  'SampleID',
  'SampleDate',
  'Organisation',
  'Voume Supplied',
  'Organisation Code',
  'Unit Of Measure',
  'Numeric Result',
  'Upper Parametric Value',
  'Lower Parametric Value',
  'Scheme Name/Supply ',
  'Scheme Code ',
  'Scheme Name/Water Supply ',
  'Year of Return ',
  'Population Serve',
  ' Result',
  ' Parametric Value',
  'Parameters',
  'EOF']
module.exports = headers
