let organisationname = [ 'Carlow County Council',
  'Cavan County Council',
  'Clare County Council',
  'Cork County Council',
  'Donegal County Council',
  'Dublin City Council',
  'Dun Laoghaire Rathdown County Council',
  'Fingal County Council',
  'Galway City Council',
  'Galway County Council',
  'Kerry County Council',
  'Kildare County Council',
  'Kilkenny County Council',
  'Laois County Council',
  'Leitrim County Council',
  'Limerick City and County Council',
  'Longford County Council',
  'Louth County Council',
  'Mayo County Council',
  'Meath County Council',
  'Monaghan County Council',
  'Offaly County Council',
  'Roscommon County Council',
  'Sligo County Council',
  'Tipperary County Council',
  'Waterford City and County Council',
  'Westmeath County Council',
  'Wexford County Council',
  'Wicklow County Council' ]
module.exports = organisationname
