'Bagenalstown',
'Bilboa',
'Borris',
'Carlow Central Regional',
'Carlow North Regional ',
'Carlow Town',
'Currenree',
'Hacketstown',
'Leighlinbridge',
'Old Leighlin',
'Slyguff',
'Tullow',
'Tynock',
'Glynn/St Mullins',
'Ballinabrannagh',
'Arvagh P.W.S. ',
'Bailieboro R.W.S.S.',
'Belturbet P.W.S.',
'Blacklion P.W.S.',
'Cavan R.W.S.S.',
'Swanlinbar P.W.S.',
'Aughadreenagh National School',
'Drumcrauve national school',
'Drumkilly National School',
'First Steps preschool',
'Kilnaleck playgroup',
'Little Gem Montessori, Enagh, Beglieve, Bailieborough',
'St Mary's National School, Drung',
'Annagh Group Scheme',
'Barraghy',
'Cavan Rd. No. 2',
'Corlough',
'Crossdowney',
'Dernakesh',
'Kildallan',
'Milltown',
'Ballymagauran',
'Ennis PWS',
'Ennistymon RWS',
'Killadysert PWS',
'Limerick City Council RWS',
'Ballingaddy PuGWS',
'Carrigerry PuGWS',
'Coolmeen PuGWS',
'Cree, Clonwhite, Clonina PuGWS',
'Cross, Kilbaha PuGWS',
'Spancillhill/Clooney PuGWS',
'Boston National School',
'Caherconnell Stone Fort, Kilfenora',
'DysertO'Dea Castle',
'ESB Power Station, Ardnacrusha',
'Lough Derg Holiday Homes, Carrownakilly, Killaloe.',
'Rahona Lodge Caravan Park',
'Steiner School, Tuamgraney.',
'Fanore',
'Killone',
'Monreagh',
'Ranaghan',
'W.Clare RWS (New WTP)',
'Shannon/Sixmilebridge RWSS',
'W.Clare RWS (Old WTP)',
'OBriens Bridge PWS',
'Corofin PWS',
'Scarriff PWS',
'Miltown Malbay PWS',
'Killaloe PWS',
'Carrownteedaun PuGWS',
'Leitrim/Shyan PuGWS',
'Clohanes PuGWS',
'Killimer PuGWS',
'Seafield PuGWS',
'Carnanes/Leadmore PuGWS',
'Querrin PuGWS',
'The Inn at Dromoland',
'East Clare Holiday Village, Bodyke',
'Beckmann Coulter',
'Shannon Airport',
'Toonagh/Dysart',
'Kilnaboy',
'Kilmaley/Inagh',
'Lisseycassey',
'Aghavrin',
'Airport Cottages',
'Ballinagree',
'Ballinamona',
'Ballingeary',
'Ballyverane ',
'Bantry Derryginagh',
'Burnfort',
'Bweeng',
'Carrigcleena',
'Carrignadoura',
'Castlecooke',
'Castlewrixon',
'City Import(Coole East-Churchfield High mixed supply) ',
'Clash/Leamleara',
'Clonakility',
'Cockhill',
'Cork Harbour & City ',
'Cregane',
'Cullen',
'Derry',
'Drimoleague',
'Dromahane',
'Dunmanway',
'Glenduff',
'Glenleigh ',
'Inch',
'Kealkill',
'Kilcolman',
'Kilmurry (Mitchelstown)',
'Kiskeam',
'Knockburden',
'Knockdrumaclough',
'Lyre Clonakility',
'Macroney',
'Macroom ',
'Midleton ',
'Monabricka',
'Monanig',
'Monaparson',
'Monee',
'Mountain Barracks',
'Newcestown',
'Ratharoon',
'Rockchapel',
'Skahanagh',
'Skibbereen Ballyhilty',
'Stagmount',
'Stoneview Blarney',
'Toormore',
'Abbey Hotel Ballyvourney',
'Absorbent Minds Montessori Pre-school Knockanroe',
'Anglers Rest',
'Ballinakilla NS',
'Bere Island Heritage Centre Bere Island',
'Berrings NS',
'Bishopscourt Residential Care',
'Bits n Bites,(Helen Ahern),Park Mountain,Tallow',
'Blarney Caravan and Camping',
'Bridge Shop,Toones Bridge,Macroom',
'Cappabue N.S. Kealkill Bantry',
'Carol Murray,Glenbower House,Kildinan',
'Carrig Ri Leamleara',
'Castlenalacht N.S. bandon',
'Cill Eanna Bar',
'Cloghboola National School',
'Clonvilla Caravan Park',
'Corbett Court Kilworth',
'Crossroads Bar,Knockavilla,Upton',
'Dannann Organics,Ruhill,Boherbue',
'Dept Defense Bere Isl',
'Derryclough N.S. Bandon',
'Donoughmore Community Playgroup, Donoughmore',
'Dreeny N.S. Skibbereen',
'Dromclough N.S. Drumclough East Bantry',
'Elaine Murphy Barry,Ballykeating,Kildorrery',
'Fermoy Golf Club,Corrin,Fermoy',
'Frankfield House Golf Club',
'Garraneassig NS',
'Glandore Nat. Sch.',
'Glenlohane B and B, Castlemagnier',
'Glenview Motors Ardnacrusha Clondrohid',
'Goggins Hill NS',
'Green Glens Arena, Millstreet',
'Halfway Bar,Tallow Road Youghal',
'Hickeys Bar Mount Uniake',
'Hi-Land,Newmarket',
'Howards Shop Lakevale Ballydesmond',
'Inch NS',
'Kart World Watergrasshill Old Well',
'Kellehers Gortnalucha Clondrohid',
'Kilbrin Community Centre',
'Kildinan Farm,Kildinan',
'Knockavilla NS',
'laragh N.S. Bandon',
'Lees Centra,Mallow',
'Letter Garden,Letter West, Kilcrohane',
'Mathey NS',
'McCarthys Caravan Park Tragumna',
'Miles Cattell,Riverstick',
'Millstreet Country Park',
'Milsean Chocolates,Careys Cross,Bandon',
'Monaflugh NS',
'Mons Bar Lissacrassig Macroom',
'National Rowing Centre,Inniscarra',
'Nazareth House Mallow',
'New Golden House Chinese Rest. Lissarda',
'Old Halfway House Mallow Road Rathduff',
'O'Mahonys Bar,Burnfort',
'park school Youghal',
'Powers Pub Mt Uniacke',
'Railway Bar,Mourneabbey',
'Real Olive Co Toons Bridge Macroom',
'Ring view bar Carrigtwohill',
'Rumley s Open Farm,Waterfall',
'S.N.Cnoc Sceach,Clan na Caoilte',
'Scoil naomh Faoinan Novohal',
'Sextons Caravan Park Timoleague',
'Shady Hollow B and B Mallow',
'Shor-en-sweet,Enniskeane',
'Speckled door Old Head of Kinsale',
'Strawbale cheese cuslora Carriganimma',
'Sullivans Shop,Barrells Cross,Kinsale',
'Sunnyside Fruit Farm Rathcormack',
'Tarelton N.S.',
'The Garden Pavillon,Ballygarvan',
'The Hotel Bere Island',
'The Lookout Cafe Bere Island',
'The Old Head Bar and Restaurant,Kinsale',
'The Swallow Inn, Araglin, Killworth',
'The White House Gallery and cafe,Kilcrohane',
'The Workshop,Ballygarvan',
'Tir na Si,Watergrasshill',
'Top Racecourse Service station mallow',
'Tracton Community Playgroup,Minane Bridge',
'Upper Glanmire NS',
'Watergrassshill Montessori',
'Whitechurch Community Centre',
'Woods Pub Lisgould',
'Ballingurteen',
'Caherdrinny',
'Clonmult',
'Downing',
'Farran',
'Gortroe',
'Insemore/insbeg',
'Rossmore',
'Leap',
'ARRANMORE ISLAND',
'BALLYSHANNON',
'CARNDONAGH (MIXED SUPPLY)',
'CARRIGART-DOWNINGS',
'CASHILARD',
'CRANFORD',
'CREESLOUGH',
'FANAD EAST (SHANNAGH)',
'FINTOWN',
'FROSSES-INVER',
'GLENTIES-ARDARA',
'GORTAHORK-FALCARRAGH',
'GREENCASTLE',
'INISHOWEN EAST',
'INISHOWEN WEST',
'LETTERKENNY',
'LETTERKENNY MIXED',
'LOUGH MOURNE',
'Owenteskna',
'PETTIGO PUB',
'PORTNOO-NARIN PUB',
'RATHMULLEN PUB',
'ROSSES REGIONAL PUB',
'BALLYMAGROARTY',
'CHURCHILL',
'GLENEELY',
'Bacus Ui Bhaoill',
'EDINFEAGH NATIONAL SCHOOL',
'Errigal Youth Hostel, ',
'Gallaghers Bakery Ardara',
'GLENVEAGH NO. 1',
'GLENVEAGH NO. 2',
'Mount Errigal Hotel',
'Oceanview Caravan Park',
'Roartys Shop/Garage Dunlewey',
'Tul na Ri Carndonagh',
'TORY ISLAND',
'TOWNAWILLY',
'DERRYKILLEW (BALLYSHANNON) (N.I.)',
'LOUGH DERG (ISLAND)',
'HARVEY'S POINT HOTEL',
'Great Northern Hotel.',
'Hollyrood Hotel',
'Mc Brides Caravan Park Meelmore',
'DCC_ZONE1',
'DCC_ZONE2',
'DCC_ZONE3',
'DCC_ZONE4',
'DCC_ZONE5',
'DCC_ZONE6',
'DLR_ZONE8',
'DLR_ZONE7',
'DLR_ZONE6',
'DLR_ZONE5',
'DLR_ZONE3',
'DLR_ZONE2',
'DLR_ZONE1',
'F_ZONE1',
'F_ZONE3',
'Topaz Garage Lissenhall Swords',
'Galway City Council Public Water S.S.',
'Ballinasloe Public Supply',
'Ballyconneely P.S.',
'Ballygar P.S.',
'Carna/Kilkieran RWSS',
'Carraroe PWS',
'Dunmore/Glenamaddy P.S.',
'Glenamaddy',
'Inishmore - Cregacareen',
'Leenane P.S.',
'Letterfrack PWS(Dawros)',
'Teeranea/Lettermore P.S.',
'Tuam RWSS',
'Williamstown PS',
'Aillebrack GWS',
'Annaghdown',
'Clooncun, Glenamaddy',
'Criminagh/Lettermore',
'Knockmascahill',
'Lettermullen No.2',
'Mannin',
'Murvey/Dolan',
'Anbally & District GWS',
'Ardrahan, GWS',
'Ballyaneen Rakerin GWS Co-Operative Society Ltd',
'Barnaderg Gortbeg GWS Co-Operative Society Ltd',
'Belclare',
'Belmont (Kilconly)',
'Caherlea / Gurrane',
'Carramore-Knock.',
'Claren/knocklehard',
'Claretuam',
'Cloonkeen/Toomard',
'Clough/Cummer',
'Coole GWS',
'Corohan Group Water Scheme',
'Gurteen/Cloonmore',
'Inismeain',
'Kilcooley (Gurtymadden)',
'Looscaun',
'Lydacan GWS Co-op Society Ltd',
'Roo',
'Seehan, Gort',
'Tierneevin',
'Tubber',
'Boyounagh / Ballyedmond - Woodfield',
'Kilconieran GWS Co-Op Society Ltd',
'Ballymanagh, Craughwell',
'Tynagh GWS',
'Rusheens',
'Rhynn/Killeeneen',
'Newcastle (Aughrim)',
'Moyglass, Loughrea.',
'Lowville No.1',
'Lisananey/Liskeavy',
'Lettergesh/Mullaghgloss',
'Kylemore Abbey',
'Kiltevna',
'Kilchreest',
'Keelogue',
'Feigh East & West',
'Esker/ Eyrecourt',
'Cluide, Cahermorris.',
'Cloonluane (Renvyle)',
'Cloonigney',
'Cloonatleva',
'Cahermorris, Corrandulla.',
'Carhereenlea, Athenry.',
'Caherdine/Caherdevan',
'Bullaun, Tuam',
'Brockagh/Lisduff  Craughwell.',
'Brierfield No1, Ballinasloe',
'Boyounagh/Ballyedmond - Gortgarrow',
' Ballintermon 003D',
'An Baile MÃ³r  PWSS 012D',
'An ClochÃ¡n PWSS 028D',
'An Daingean PWSS  030D',
'An Fheothanach PWSS',
'An Ghleann PWSS  039H',
'An MhÃ­n Aird  No . 1 PWSS 060D',
'An MhÃ­n Aird No. 3 PWSS 090D',
'An MhuirÃ­och/ Baile Breach PWSS 063D',
'Ardfert North PWSS 003E',
'Baile an FheirtÃ©araigh PWSS 011D',
'Baile an Sceilg PWSS 008H',
'Barraduff PWSS 602E',
'Brosna/Knocknagoshel PWSS 016F',
'Caherdaniel PWSS 019H',
'Cahersiveen PWSS 017H',
'Camp PWSS 020D',
'Caragh Lake PWSS 022A',
'Castlecove PWSS 023H',
'Castlegregory PWSS 024D',
'Cathair BÃ³ Sine PWSS 018D',
'Central Regional : Ballintobeenig 401F*',
'Central Regional : Ballymacadam 402F*',
'Central Regional : Killsarkin 403F*',
'Central Regional : Knocknageeha Gneeveguilla 407F*',
'Central Regional : Lisloose 405F*',
'Central Regional : Lissardboola 404F*',
'Central Regional : Sheheree 408F*',
'Central Regional: Lough Guitane (H)  400F',
'Central Regional: Scart 406F*',
'Cill MaoilchÃ©adair PWSS 047D',
'DÃºn Chaoin  PWSS 034D',
'Dromin : Listowel 601E*',
'Dromin: Ballybunnion 605E*',
'Dromin: Ballyduff 602E*',
'Dromin: Ballylongford 603E*',
'Dromin: Scartleigh(H) 600E',
'Dromin: Tarmons 604E*',
'Emlaghpeasta PWSS 035H',
'Fenit PWSS 037D',
'Glenderry PWSS 076E',
'Inch PWSS 044D',
'Kenmare PWSS 045A',
'Kilgarvan PWSS 046A',
'Lauragh PWSS 051A',
'Lyreacrompane RWSS 057E',
'Maulin PWSS 066H',
'Mid Kerry : Gearha (H) 300A',
'Mountain Stage PWSS 062A',
'Portmagee PWSS 064H',
'Shrone PWSS 078A',
'Sneem PWSS 068A',
'TÃ­r Abhainn Thoir PWSS  091D',
'Templenoe PWSS 073A',
'Waterville PWSS 075H',
'Abbeydorney / Killflynn GWSS 01',
'Ardteegalvin  GWSS 9904',
'Caherfilane',
'Castlequin GWS',
'CilÃ­n Liath',
'Clanmaurice  GWSS Yy01',
'Commaun   GWSS 321J (PS)',
'Coolkeragh GWSS  0207',
'Cordal/Killmurray GWSS Gs23',
'Corran  Gs25',
'Curraheen GWSS 27  (PS)',
'Dawros GWSS 31',
'Knockeen GWSS 37',
'Lyreacrompane GWSS 45',
'Muingaphuca GWSS 48',
'Spa/Tiernaboul GWSS 60',
'Dingle Brewery, Spa rd, An Daingean',
'Dingle Distillery, Milltown, An Daingean',
'Michael Fitzgerald, The Junction Bar,  Camp',
'O'Gradys B&B, Spunkane, Waterville',
'The Scarriff Inn,Caherdaniel',
'An GhrÃ¡ig',
'Bonane GWSS 12',
'Cappanalea GWSS',
'Derrynane GWSS C669',
'Inch/Foildaun GWSS 36',
'Kells GWSS 9906',
'Toor GWSS',
'Tuosist GWSS',
'Lyranes 303A',
'Dromin: Moyvane 601E*',
'Mid Kerry: Knocknavota 302A*',
'Mid Kerry: Barleymount 301A*',
'Breanlee PWSS 088A',
'Ceann trÃ¡ PWSS 074D',
'Baile na BhFionnÃºrach PWSS 006D',
'Aughacasla  PWSS 005D',
'Rathmore PWSS 065A',
'Tieraclea (Tarbert) PWSS 071E',
'Lahesheragh  PWSS 080E',
'Ardfert South PWSS  004F',
'Brosna / Knocknagoshel GWSS 9901',
'Asdee GWSS',
'Breadcrumb Bakery, Kenmare',
'Blasket View , Doora, Portmagee',
'Daly's Bar, Camp',
'Ballyseedy Castle Hotel, Ballyseedy, Tralee',
'Sea View Caravan park, Kells bay',
'North Carlow South Kildare Regional',
'Clogherinkoe',
'Clonuff',
'Poulaphouca Regional',
'Rathangan',
'Ballyna Estate Development Moyvalley',
'Broadford NS',
'Cadamstown NS',
'GAA Eadestown',
'Lios an Ri, Clogherinka',
'Ballindoolin GWS',
'Ballyroe/Leinster Lodge',
'Castlehill Estate WS 1021, Coan',
'Clogh-Castlecomer WS 1005',
'Gorteen Ws 1016',
'Gowran-Goresbridge-Paulstown WS 1007',
'Inistioge WS 1009',
'Kilkenny City (Radestown) WS 1010',
'Kilkenny City (Troyswood) WS 1011',
'New Houses WS 1022, Callan Road, Kilmanagh',
'Paulstown - Choill Rua WS 1024',
'Ardra GWS',
'Coolhill-Cullentragh GWS',
'Hermitage GWS',
'Ballygown Piltown - A Slice of Heaven',
'Ballyouskill - Over the rainbow montessori',
'Barna - Kyleview Tavern',
'Bigwood - National School',
'Brambelstown Gowran, Marys Domestic Baking',
'Callan - Bolton Woods Development',
'Castlecomer - Clogh Fountain',
'Castlecomer - Deerpark Fountain',
'Cellarstown-Billy Deegan - Roots and Fruits Production',
'Conahy - National School',
'Coolcullen - Larkin',
'Coolcullen- Hillview Home Baking',
'Coon - Coon Hall',
'Coon - National School',
'Coon - Strand Bar',
'Croan Holiday Cottages',
'Drakelands - Mis en Place Food Production Industry',
'Dunbell - Connolly',
'Dunmore Caves, Coffee Shop',
'Firoda - National School',
'First Impressions Playschool, Willow Pond House',
'Gathabawn - Sheehy',
'Glanbia Consumer Foods, Coolnacrutta, Johnstown',
'Goresbridge - Appletree Farm Montessori School',
'Gowran Bricana Orla Hughes Just Cakes',
'Hugginstown - Cleary',
'Hugginstown - Pre school Listimague',
'Inistioge - Woodstock Tea Rooms',
'Kate Creed Food Producer - Clonamery Thomastown',
'Kells - Burgess Court Housing Development',
'Kilfane - Long Man',
'Kilkenny - Aspect Hotel',
'Kilkenny - Glanbia Soups',
'Kilkenny - Kilkenny Frozen Foods',
'Kilkenny College - Castlecomer Road',
'Killamery - Auld House',
'Kilmanagh - Post Office',
'Knocktopher - Carrolls Centra, Tap in shop',
'Knocktopher - Whitescastle Housing Development',
'Listerlin - National School',
'Listerlin - Ryan',
'Little Acorns Preschool Flower Hill Rosbercon',
'Monroe National School',
'Newmarket - Hunterswood Housing Estate',
'Newrath - Waterford Golf Club',
'Piltown - Mileeven Honey',
'Piltown - Sugradh Tobernabrone',
'Piltown National School',
'Ringville - National School',
'Shanbogh -  National School',
'Slieverue - Rathpatrick - Euro Fuels',
'Slieverue - Rhu Glen Country Club',
'The Rower - Tinnaslatty, Bernies Farmhouse Desserts',
'Thomastown - Cloughsgregg -Joan & Bobs Juicy Jams',
'Thomastown - Stroan Fountain',
'Thomastown -Newtoan Fountain',
'Tinneranny - New Ross Golf Club',
'Truck Centre, Freshford Road, Kilkenny',
'Vehicle Centre, Callan Road, kilkenny',
'Woodstock Play School and Montessori Woodstock Lodge',
'Barna-Kilrush GWS',
'Baunmore GWS - Walshs Well',
'Kilree Stoneyford GWS',
'Urlingford - Industrial Estate',
'Clonaslee PWS',
'Mountrath PWS',
'Portarlington PWS',
'Portlaoise PWS',
'Dereen Durrow PuGWS',
'Arles - Commumity Centre ',
'Barrowhouse GAA SPS',
'Camross Inn',
'Dunnes Garden Centre, Durrow',
'Heritage golf club Killenard',
'Jimmy Mulhall',
'Killenard Lodge',
'Killenure National School',
'Maganey Industries',
'Mount Henry Estate, Killenard',
'Pike of Rushall National School',
'Rath Primary School',
'Spink GAA Grounds',
'Suaimhnoag ',
'Ballymaddock PrGWS',
'Cullahill PRI',
'Lough Borehole Supply PWS',
'Arles 2 PWS',
'Durrow 2 PWS',
'Abbeyleix 2 PWS ',
'Ballinakill 2 PWS',
'Mountmellick 1 PWS',
'Ballinakill 1 PWS',
'Rosenallis PWS',
'South East Regional PWS',
'Ballyroan PWS',
'Graigcullen PWS',
'Mountrath 3 PWS',
'Abbeyleix 1 PWS',
'Mountrath 2 PWS',
'Rathdowney PWS',
'Swan PWS',
'Borris in Ossory PWS',
'Durrow 1 PWS',
'Portarlington 2 PWS',
'Meelick PWS',
'Derrylamogue N.S.',
'Clonnany PuGWS',
'Ballybrophy PuGWS',
'Crannagh (Phase 1) PuGWS',
'The Rock PuGWS',
'Ballyadams PuGWS',
'Clonkeen/Fermoyle PuGWS',
'Sleaty Road PuGWS',
'Killamuck PuGWS',
'Attanagh PRI',
'Ballacolla PRI',
'Ballypickas PRI',
'Barrowhouse PRI',
'Donaghmore PRI',
'Errill PRI',
'The Heath PRI',
'Carriglea',
'Coolnaboul PuGWS',
'Camross N. S.',
'Ballycleary PuGWS',
'Moyanna PuGWS',
'Knockbeg College',
'Heritage Hotel, Killenard',
'Blackhill PuGWS',
'Knock N. S.',
'Raheen PuGWS',
'Killadooley National School',
'Barnashrone National School',
'Barrowhouse N. S.',
'Arles Primary School',
'Killeen Primary School',
'Dowra',
'North Leitrim Regional Water Supply',
'South Leitrim Regional',
'Ardlogher/Cornagher',
'Keeldra No. 2',
'School road/Black road',
'Glenboy/Glenfarne GPU',
'Toomans/Clooncumber',
'Drumaleague',
'Cornashamsoge',
'Cloncolry',
'Lisdrumfarna/Lisdrumrea',
'Cloonaquin',
'Lisdadan/Tawaymore',
'Drumraine/Costra',
'Toomans/Gortnagullion',
'Lisduff/Cornaslieve',
'Cartown',
'Drumharkin/Drumroosk',
'Effernagh',
'Drumany/Corrabeagh',
'Bellanaboy',
'Cornageeha',
'Castleroggy',
'Corrawallen',
'Tawnyfeacle',
'Keelagh/Bornacoola',
'Loughside',
'Mullaghgarve/Aghacashel',
'Kilmaddaroe',
'Corraterrif',
'Glencar Gpu',
'Cloonturk',
'Hartley/Cloonshebane',
'Mullaghboy/Drumbranned',
'Cloone',
'Mohercregg',
'Leitrim Village',
'Cornabrone/Aughaslan',
'Aughnasheelan',
'Fearglass',
'Lough Erril',
'Cloonsarn',
'Ballinagleragh',
'Miskaun',
'Anfield GWS',
'Cleenahoo/Lisnatullan',
'Drumbohar/Drumgowla',
'Oghill',
'Gorvagh/Drumloan',
'Kilbracken',
'Gortlettragh',
'Fawn/Killarkin',
'Rossinver/Dooard',
'Dartry No. 2',
'Corraleehan',
'Aughawillan',
'Aughavas',
'Carrigallen GWS',
'Kinkeen',
'Tarmon ',
'ABBEYFEALE PUB DWS',
'FEDAMORE PUB DWS',
'LIMERICK CITY ENVIRONS PUB DWS',
'Lisnagry Public GWS',
'Shanid Lower Public GWS',
'Athlacca National School',
'Ballyguiltenane National School',
'Clomshire Equestrian Centre, Adare',
'Crecora National School',
'Kilcolman National School',
'BARNAGH/GLENDARRAGH PVT GWS',
'BULGADEN PVT GWS',
'Limerick City Water Supply',
'KILEEDY PVT GWS',
'KILFINNEY PVT GWS',
'FEOGHANA/CASTLEMAHON PUB GWS',
'LOUGH GUR PVT GWS',
'Towerhill Public GWS',
'CARNANE PVT GWS',
'BALLYBRICKEN PVT GWS',
'Castleroberts Adare Public GWS',
'CAPPAGH PVT GWS',
'NEWTON/CAHERLINE PVT GWS',
'ADARE PUB DWS',
'BALLINGARRY PUB DWS',
'BALLYLANDERS PUB DWS',
'BRUFF PUB DWS',
'BRUREE PUB DWS',
'CAHERCONLISH PUB DWS',
'CROOM PUB DWS',
'DOON PUB DWS',
'FOYNES/SHANNON ESTUARY PUB DWS',
'GLIN PUB DWS',
'KILMALLOCK PUB DWS',
'KNOCKLONG PUB DWS',
'MURROE PUB DWS',
'NEWCASTLE WEST PUB DWS',
'OOLA PUB DWS',
'PALLASGREEN PUB DWS',
'RATHKEALE PUB DWS',
'HOSPITAL PUB DWS',
'South West Regional PUB DWS',
'Cappamore Foileen Public Water Supply',
'Ardpatrick Kilfinnane Public Water Supply',
'BALLYMAHON',
'GOWNA',
'GRANARD',
'LONGFORD CENTRAL',
'Anglers Rest, Mullinalaghta',
'Brid Mulfaul, Mullinalaghta',
'Camlin Service Station, Dublin Rd.,',
'Keoghs, Mullinalaghta',
'Kevin McDonagh',
'Winnie the Pooh, Montessorie',
'Clonmore/Kilmore',
'Fostra',
'LANESBORO',
'NEWTOWNCASHEL',
'Cavanhill',
'Rosehall',
'Kilanny/Reaghstown',
'ACHILL RWSS',
'BALLINA RWSS',
'BALLYCASTLE WSS',
'BONNICONLON WSS',
'CROSSMOLINA WSS',
'KILMAINE WSS',
'KILTIMAGH WSS',
'LOUGH MASK RWSS',
'LOUISBURGH WSS',
'NEWPORT WSS',
'SWINFORD WSS',
'WESTPORT WSS',
'CRIMLIN/ROSS pGWS',
'RATHCASH pGWS',
'TREENKEEL pGWS',
'Betty Rose Cupcakes, Murrisk',
'Cloona Health Retreat, Cloona',
'GLENKEEN FARM, LOUISBURGH',
'Kirstin McDonagh, Knappagh',
'Mescan Brewery, Kilsallagh',
'SPS - ASHLEAGH LODGE',
'SPS - CAMPBELL'S BAR, MURRISK',
'SPS - CLAIRE KEARNS PUB, LECANVEY',
'SPS - CLARE ISLAND LIGHTHOUSE',
'SPS - CROUGH PAT COMMUNITY CAFE',
'SPS - CROUGH PATRICK'S INFORMATION CENTRE',
'SPS - DUFFYS GROCERY',
'SPS - FLANAGAN'S BAR, BRICKEENS',
'SPS - GIBBONS FOODSTALL, MURRISK, WESTPORT',
'SPS - HEALY'S HOTEL PONTOON',
'SPS - OLD HEAD BAR, LOUISBURGH',
'SPS - STAUNTON'S BAR, LECANVEY',
'SPS - THE LARCHES, FINNEY',
'SPS - THE TAVERN BAR, MURRISK',
'AILLE GWS (AYLE)',
'BARNEYCARROLL GWS',
'BRACKLOON/SPADDAGH GWS',
'BUCKOOGH/FURNACE GWS',
'CALLOW LAKE GWS',
'CUSHIN GWS',
'IRISHTOWN GWS',
'JOHNSTOWN GWS',
'KILLASSER GWS',
'KILLGALLIGAN GWS',
'KILMEENA GWS',
'KILMOVEE/URLAUR GWS',
'Lough Carra GWS',
'MIDFIELD GWS',
'NEPHIN VALLEY GWS',
'PARKE GWS',
'POLLAVADDY GWS',
'ROBEEN GWS',
'ROSMONEY GWS',
'ROSSPORT GWS',
'ROY BINGHAM'S GWS',
'SRAHEEN GWS (FOXFORD)',
'TREANNAGLERAGH GWS',
'Ballina-Lisglennon',
'Farnaught pGWS',
'PBKS GWS',
'MOYLOUGH pGWS',
'MOYLAW GWS',
'DRUMMINDOO FAHY GWS',
'Clew Bay GWS',
'KINLOUGH GWS',
'MOUNT JUBILEE pGWS',
'GLENCASTLE pGWS',
'Carranaradh Pgws',
'COMMINCH',
'DRUMMINROE (WEST) pGWS',
'SRAH pGWS',
'BALLYFARNAGH/MAGHERABOY pGWS',
'CUSLOUGH pGWS',
'BRACKLOON/BOHEA pGWS',
'GORTEEN (SHRULE) pGWS',
'LECARROW (BALLYHAUNIS) pGWS',
'DELVIS/KNOCKBRACK pGWS',
'DERRY pGWS',
'POLLROHANAN pGWS',
'CORDARRAGH pGWS',
'DOOYORK pGWS',
'TULLAGHANDUFF/BAWN pGWS',
'TALLAGH HILL pGWS',
'NORTH COAST pGWS',
'ROSS pGWS (BALLINA)',
'BALLYSAKERRY pGWS',
'CARRAS DISTRICT pGWS',
'KEENAGHBEG (KEENAGH) GWS',
'CURRAMORE (BALLINROBE) GWS',
'TULLAGHBAWN GWS',
'CRUMPAUN pGWS',
'PULLATHOMAS pGWS',
'DERRYNAMEEL/DERRYCORRIB pGWS',
'FOXPOINT/BARNATRA pGWS',
'CLOONISLAUN pGWS',
'QUIGNAMANGER pGWS',
'BALLYHOLAN pGWS',
'TULLYEGAN pGWS',
'CARNE pGWS',
'MOYRAHAN pGWS',
'CLOONGEE pGWS',
'DALGAN pGWS',
'RAHARD pGWS',
'KILLAWALLA pGWS',
'CLOGHER (WESTPORT) pGWS',
'BALLINLOUGH pGWS',
'SAULIA pGWS',
'DUGORT (EAST) NO. 1 pGWS',
'DOONIVER pGWS',
'DUGORT NO.2 pGWS',
'DOOEGA pGWS',
'ARDS/CURRANE pGWS',
'MEELICKMORE pGWS ',
'ABBEYQUARTER pGWS',
'KILCOLMAN/FACEFIELD GWS',
'DOOHOMA/DERRYCORRIB pGWS',
'SRAHEEN/AUGHAGOWER pGWS',
'FUNSHINAUGH/CROSS GWS',
'LOUGHAUNNAMAN GWS',
'ERREW GWS',
'DRUMSHEEN/NEWTOWN GWS',
'DRUMMIN GWS',
'DERRYVOHY GWS',
'DOOHOMA GWS',
'CLOONMORE/CLOONLAVIS GWS',
'CLOONMORE/ROOSKEY GWS',
'TOOREEN/AGHAMORE GWS',
'LOUGH MASK CREEVAGH GWS',
'LISSATAVA  pGWS',
'LAGHTA GWS',
'KILLEEN GWS',
'KILLATURLEY GWS',
'KILGARRIFF GWS',
'GURTEEN/CARROWKEEL pGWS',
'GLENHEST GWS',
'GLENCORRIB GWS',
'ELLY/BLACKSOD pGWS',
'DRUM / BINGHAMSTOWN GWS',
'CREGGDUFF GWS',
'CURRAUNBOY GWS (CORNBOY) GWS',
'COOGUE GWS',
'BELDERG GWS',
'BELCARRA pGWS',
'BEKAN & DISTRICT pGWS',
'BALLYCROY GWS',
'ATTYMASS GWS',
'Agher',
'Anneville',
'Ballinabrackey',
'Ballinacree',
'Ballymacad',
'Baltrasna',
'Batterstown',
'Cloneycavan',
'Collierstown',
'Cookstown',
'Cottrels Garden',
'Croboy',
'Crossguns',
'Donore',
'Drumcondrath',
'Dunshaughlin',
'East Meath',
'Hollymount',
'Kells-Oldcastle',
'Kilcock PWS MCC',
'Knockmark',
'Leggagh',
'Meadowview Housing Estate Clonard',
'Moynalvey Manor',
'Navan-Mid Meath',
'Newtown/Creevagh',
'Philips Cross',
'Powerstown PWS',
'Readstown',
'Slane',
'Woodview ',
'Private Regulated Supply No. 119',
'Private Regulated Supply No. 123',
'Private Regulated Supply No. 125',
'Private Regulated Supply No. 128',
'Private Regulated Supply No. 134',
'Private Regulated Supply No. 144',
'Private Regulated Supply No. 149',
'Private Regulated Supply No. 158',
'Private Regulated Supply No. 159',
'Private Regulated Supply No. 172',
'Private Regulated Supply No. 173',
'Private Regulated Supply No. 177',
'Private Regulated Supply No. 178',
'Private Regulated Supply No. 232',
'Private Regulated Supply No. 240',
'Private Regulated Supply No. 241',
'Private Regulated Supply No. 257',
'Private Regulated Supply No. 267',
'Private Regulated Supply No. 72',
'Private Regulated Supply No.103',
'Private Regulated Supply No.110',
'Private Regulated Supply No.13',
'Private Regulated Supply No.186',
'Private Regulated Supply No.187',
'Private Regulated Supply No.192',
'Private Regulated Supply No.211',
'Private Regulated Supply No.219',
'Private Regulated Supply No.223',
'Private Regulated Supply No.38',
'Private Regulated Supply No.48',
'Private Regulated Supply No.6',
'Private Regulated Supply No.62',
'Private Regulated Supply No.64',
'Private Regulated Supply No.65',
'Private Regulated Supply No.68',
'Private Regulated Supply No.7',
'Private Regulated Supply No.73',
'Private Regulated Supply No.78',
'Private Regulated Supply No.79',
'Private Regulated Supply No.82',
'Private Regulated Supply No.87',
'Williamstown PWS',
'Abbeyfields Housing Estate Clonard',
'Ballinaclose',
'Mulhussey',
'Jarretstown',
'Irishtown/ Mabestown ',
'Nobber',
'Moynalty',
'Longwood',
'Kilmessan',
'Kilmainhamwood',
'Enfield',
'Trim',
'Dunboyne',
'Castletown (Meath County Council) ',
'Ballivor',
'Athboy ',
'Private Regulated Supply No. 513',
'Meath Hill',
'Kiltale',
'Carrickmacross',
'LERWSS',
'Donaghmoyne',
'Doohamlet',
'Stranoodan',
'Birr P.W.S.',
'Rhode RWSS P.W.S.',
'OY 12',
'OY51',
'OY56',
'OY68',
'OY70',
'SOY 4',
'SOY 6',
'SOY 9',
'Mountlucas G.W.S.',
'SOY 8',
'SOY 7',
'Arigna',
'Arigna Regional',
'Ballinlough/Loughglynn',
'Castlerea',
'Castlerea Urban',
'Grangemore',
'NERWSS - Rooskey',
'NERWSS - Tarmonbarry',
'North East Regional',
'North Roscommon Regional Water Supply Scheme',
'Roscommon Central Water Supply Scheme',
'SRRWSS - Killeglan',
'SRRWSS - Lisbrock',
'Dysart (S-Pri)',
'Mountain Ballinlough (S-Pri)',
'Onagh Taughmaconnell (S-Pri)',
'Polecat Springs',
'Hugestown',
'Castlerea Regional',
'Boyle/Ardcarne',
'Arigna Rover',
'NERWSS - Strokestown/Elphin',
'Woodbrook (S-Pri)',
'Termon Castlerea (S-Pri)',
'Slatta (S-Pri)',
'Rooskagh (S-Pri)',
'Pallas Elphin (S-Pri)',
'Kilronan/Lisacul (S-Pri)',
'Driney (S-Pri)',
'Currasalae/Lisacul (S-Pri)',
'Foxes Den Public Water Supply',
'Kilsellagh Public Water Supply',
'Lough Gill (Cairns Hill) PWS',
'Lough Talt Regional Water Supply',
'St Angela's College, Private Water Supply',
'Student Residences - St Angela's College  ',
'Carrownadargney Private Group Water Scheme',
'Corrick (Ballinafad) Private Group Water Scheme',
'Keash Private Group Water Scheme',
'SD_ZONE1',
'SD_ZONE2',
'SD_ZONE3',
'SD_ZONE4',
'Ahenny',
'Ardfinnan Regional',
'Burncourt Regional',
'Carrick-on-Suir [Crottys Lake]',
'Carrick-on-Suir [Lingaun River]',
'Clonmel Poulavanogue',
'Cloran Regional',
'Coalbrook',
'Dundrum Regional',
'Galtee Regional',
'GLENARY',
'Gortnapisha Regional',
'HOLLYFORD',
'IRONMILLS',
'KILCASH',
'Mullinbawn',
'Templetney Borehole',
'Aherlow House Hotel',
'Kilcoran house hotel',
'Knocklofty House Hotel',
'Ardcroney GWS',
'Corbally, Portroe GWS',
'Frolic/Carney GWS',
'Cantwells Quality Water',
'Glenpatrick Spring Water',
'Aherlow House Hotel (lodges well)',
'Tipperary UDC',
'Merck, Sharpe & Dohme',
'Hotel Minella',
'SPS - AIBP (Simply Foods Ltd), Borrisokane Rd, Nenagh',
'Drombane (Upperchurch) GWS',
'SPS - Arrabawn Co-op Nenagh',
'LCB Monamon',
'East Waterford Water Supply Scheme',
'Ballydermody',
'Monatarrif',
'Lacken',
'Parc an Aonaigh Kilmacthomas',
'Gort na Clochair',
'Dunhill Ballinageeragh',
'Melleray',
'Ballynoe',
'LCB Lismore',
'Moores Well',
'Ross/Kildermody',
'Bonmahon',
'Glenagad',
'Modeligo',
'Lyrenaleara  ',
'Loskeran',
'LCB Ballyduff',
'Dromore Upper',
'Crehanagh',
'Kill/Ballylaneen',
'Kilbrien',
'Villierstown',
'Touraneena',
'Tinkock\Tinnabinna',
'Tallow  ',
'Strancally',
'Stradbally',
'LCB Ballyhane',
'Scrahan',
'Russelstown',
'Roberts Cross',
'Ring/Helvick/Seaview',
'Rathgormack',
'Poulavanogue',
'Portlaw',
'Nire',
'Monadiha',
'Leagh Cross',
'LCB Cappoquin',
'Knockeylan',
'Knocklucas',
'Knockalisheen',
'Kilrossanty',
'Kilnamack',
'Kilmore-Kilbeg',
'Kilmacthomas',
'Kilgobnet',
'Kilcooney',
'Kealfoun',
'Inchinleamy',
'Graiguerush',
'Scrothea ',
'Geoish',
'Garryahylish',
'Fews',
'Feddans',
'Faha',
'Dungarvan',
'Currabaha West',
'Cooneen\Dromore',
'Clonea OSullivan',
'Castlereagh',
'Carrowgarriff',
'Carrignagower',
'Carrigeen',
'Crough',
'Comeragh',
'Boolavoonteen',
'Ballyshunnock',
'Ballysaggart',
'Ballyogarty',
'Ballymoate Upper',
'Ballyknock',
'Ballyheaphy',
'Ballyguiry',
'Ballycurrane',
'Deelish/Ballinacourty',
'Aglish',
'Castlewoods Ballinamona',
'Seanachai Holiday Homes',
'Seanachai Pub',
'Stradbally NS',
'Ronans Ardmore',
'Ardnahoe',
'St Declans School Kilmacthomas',
'Coolnasmear',
'Newtown School',
'Momminane',
'Ballydurn',
'Kill Ceol na Mara',
'Athlone WSS',
'Ballinahowen WSS',
'Ballany Low Level Reservoir',
'Frewin Hill Low Level Reservoir',
'Ardonagh Reservoir',
'Ardnapondra Reservoir',
'Killucan Reservoir',
'Mullaghmeehan Re-Chlorination Station',
'Kilbeggan Water Tower',
'Gaybrook Water Tower',
'Dysart Re-Chlorination Station',
'Delvin Re-Chlorination Station',
'Ballany High Level Reservoir',
'Multyfarnham GWSS',
'Monganstown / Clonfad / Rayhbawn GWSS',
'Hodgestown GWSS',
'Clongowney GWSS',
'Ballynacargy/Empor GWSS',
'Kilbixy GWSS',
'Raheenquill GWSS',
'Simonstown GWSS',
'Shureen / Ballymacmorris GWSS',
'Raheenmore GWSS',
'Redmondstown / Conranstown GWSS',
'Dysart / Lilliput GWSS',
'Cummerstown GWSS',
'Clonageeragh / Sallymount GWSS',
'Gartlandstown GWSS',
'Coolvuck GWSS',
'Moydrum / Baylin GWSS',
'Glor na Gaoithe, Cleariestown',
'Askamore',
'Fairfields Close Adamstown',
'Chestnut Grove',
'Aughclare, Campile',
'Raheen',
'Deerpark',
'Oldcourt',
'Tellarought',
'Ballykelly, Campile',
'Dunanore (Old Ross)',
'Galbally',
'Bola Beg (Templeshanbo)',
'Craane',
'Wilton',
'Monageer',
'Woodview Drive Adamstown',
'Wexford Town',
'Sow Regional',
'South Regional',
'New Ross',
'Marshalstown',
'Kiltealy',
'Kilmyshall',
'Enniscorthy',
'Davidstown',
'Coolgreany',
'Clonroche',
'Clohamon',
'Castledockrell',
'Bunclody',
'Bree',
'Boolavogue Housing',
'Ballyhogue',
'Ballindaggin',
'Valentia House',
'O'Rahilly View, Gusserane',
'Ban na Cheile, Cassagh',
'Brooklyn Court, Tara Hill',
'Carrig Briste PS',
'Tiny Tots PS',
'Patricias Playschool',
'Leaps and Bounds Childcare',
'Eager Beavers Montesorri',
'Craanford Playgroup',
'Castle Kids PS',
'ABC Club Carrowreagh',
'A Place to Grow PS',
'Colaiste Abbain',
'Hillview, Ballinaboola',
'Corrigene',
'Daffodil Care Services The Pines, Oulart',
'Daffodil Care Services Fuchsia Lodge, Hollyfort',
'Blackstairs Group',
'Monaseed NS',
'Tombrack NS',
'Tara Hill NS',
'Prospect Holiday Park, Ballymoney Gorey',
'Rathgarogue NS',
'Clones CP, Clones, Castletown, Gorey',
'Oulart NS',
'O Loughlins PRI',
'Ocean Island CP PRI',
'Monageer NS',
'Marshalstown NS',
'Knockina Group',
'Kilnamanagh NS',
'Horeswood national Schools PRI',
'Gusserane NS',
'Galbally NS',
'Davidstown NS',
'Adamstown Group',
'Craanford NS',
'Courtnacuddy NS',
'Clologue NS',
'Castletown NS',
'Castledockrell NS',
'Carrowreagh NS',
'Boolavogue NS',
'Ballythomas NS',
'Ballyroebuck NS',
'Ballyfad NS',
'Ballyellis NS',
'Ballyduff NS',
'Adamstown NS',
'Carne CP (Ray Doyle), Carne',
'Ardamine CP (H Farrell)',
'Oatfields Leisure Park (Boggans) Morriscastle',
'Killinieran Group',
'Morrisscastle Village Estate',
'Knockavilla, New Ross',
'Rathdowney CP',
'LOUGHMOGUE PUBLIC SUPPLY',
'STRANAKELLY PUBLIC SUPPLY',
'BALLYKILMURRAY PUBLIC SUPPLY',
'KNOCKNAGILKY PUBLIC SUPPLY',
'MULLANS NORTH PUBLIC SUPPLY',
'BALLINGLEN (PREBAN BRIDGE) PUBLIC SUPPLY',
'BALLYMORRIS (FORT FAULKNER) PUBLIC SUPPLY',
'JOHNSTOWN SOUTH (ARKLOW) PUBLIC SUPPLY',
'KILBALLYOWEN(AUGHRIM) PUBLIC SUPPLY',
'BERRYFIELD LANE PUBLIC SUPPLY',
'KILLAVANEY PUBLIC SUPPLY (TINAHELY)',
'KILLAVANEY PUBLIC SUPPLY (ARKLOW)',
'BALLINAPARK PUBLIC SUPPLY',
'WINDGATES TEMPLECARRIG PUBLIC SUPPLY',
'AVOCA BALLINACLASH PUBLIC SUPPLY',
'AUGHRIM ANNACURRA PUBLIC SUPPLY',
'HOLLYWOOD DONARD PUBLIC SUPPLY',
'DUNLAVIN PUBLIC SUPPLY',
'ENNISKERRY PUBLIC SUPPLY',
'BLESSINGTON PUBLIC SUPPLY',
'NEWTOWN NEWCASTLE PUBLIC SUPPLY',
'WICKLOW REGIONAL SUPPLY',
'GREYSTONES PUBLIC SUPPLY',
'BRAY DIRECT PUBLIC SUPPLY',
'Cookie Wonders',
'Boswell Equestrian Centre',
'Marcella Cremin',
'Devils Glen Equestrian Village',
'Killisky Breads',
'POWERSCOURT KIOSK',
'LOUGHDAN B&B',
'LITTLE MUNCHKINS',
'GREENAN FARM PRIVATE SUPPLY',
'RIVERSDALE B&B PRIVATE SUPPLY',
'Tony Harte',
'Mollys Larder',
'Mary Anne Douglas Home Bakery',
'Stonehaven Chutney',
'Roundwood Montessori',
'Joan Woolmington',
'S Phelan Ballygannon More Preschool',
'Merck Sharpe Dome',
'DISNEY ICES',
'FRANCES LITTLE FLOWERS',
'ARKLOW TOWN FOOTBALL CLUB',
'THE FARM SHOP TINAHELY',
'STOOPS GUESTHOUSE',
'STEPPING STONES PRESCHOOL',
'AURORA HOSTEL',
'GLENCREE CENTRE FOR RECONCILIATION',
'AN OIGE HOSTEL KNOCKREE',
'ROUNDWOOD INN',
'CHOCOLATE GARDEN RATH',
'GOODLIFE FOOD COMPANY',
'BALLYKNOCKEN HOUSE & COOKERY SCHOOL',
'GERTIE SALLY BALLYMOYLE LANE',
'ANNACURRA DEVELOPMENT LTD (HAZEL HILL HOUSING ESTATE) ',
'EARTH ANGELS ',
'LITTLE RED HEN PLAYGROUP',
'LITTLE LADYBIRDS PLAYGROUP',
'KOLIBA B&B (AVOCA)',
'BUTLERS B&B (REDNAGH HILL)',
'Arklow Rugby Club',
'LISCOLMAN PRESCHOOL',
'JENNYS PRESCHOOL (MONEYSTOWN)',
'TALLONS PUB STRATNAKELLY PRIVATE SUPPLY',
'DOYLES BALLINGLEN',
'BYRNES PUB CRAB LANE COOLKENNO PRIVATE SUPPLY',
'BALLYBEG HOUSE (BALLINGLEN)',
'JOHNSTOWN (HOLLYWOOD) PRIVATE GWS',
'TULFARRIS RESORT PRIVATE WATER SUPPLY',
'BALLYCONNELL NATIONAL SCHOOL',
'GLENMALURE GOLF CLUB PRIVATE SUPPLY',
'CLOGGA HOLIDAY HOMES',
'TINAHELY SHOWGROUND',
'TEMPTING TREATS PRIVATE SUPPLY',
'COOLMONEY ARMY CAMP',
'BARNDARRIG SERVICE STATION',
'BRITTAS BAY VILLAGE',
'RATHWOOD GARDEN CENTRE',
'COOLATTIN GOLF CLUB',
'BALLYNACARRIG NATIONAL SCHOOL PRIVATE SUPPLY',
'BLAINROE GOLF CLUB ',
'WOODENBRIDGE HOTEL',
'ASGARD NURSING HOME, KILBRIDE, ARKLOW',
'WOLOHANS CARAVAN PK',
'REUTERS CARAVAN PARK',
'KAVANAGHS HOLIDAY HOMES PRIVATE SUPPLY',
'LEAHYS CARAVAN PARK',
'JACKS HOLE CARAVAN PARK',
'BALLINACARRIG CARAVAN PARK',
'ARKLOW CARAVAN PARK',
'BLAINROE PRIVATE GWS',
'CORNAGOWER EAST PRIVATE GWS',
'BLAKESTOWN BRITTONSTOWN PRIVATE GWS',
'GORMANSTOWN PRIVATE GROUP WATER SCHEME',
'TINODE PRIVATE GROUP WATER SCHEME',
'BALTYBOYS HUMPHRYSTOWN PRIVATE GROUP WATER SCHEME',
'BALLINGATE PRIVATE GWS',
'ASKANAGAP PRIVATE GWS',
'GLEESONS CARAVAN PARK PRIVATE SUPPLY',
'HIGGINS CARAVAN PARK',
'HILLS CARAVAN PARK',
'JOHNSONS CARAVAN PARK',
'MCDONALDS CARAVAN PARK',
'O DRISCOLLS CARAVAN PARK PRIVATE SUPPLY',
'OLIVER STAUNTON CARAVAN PARK',
'WILLIAMS CARAVAN PARK ',
'WOODENBRIDGE GOLF CLUB',
'BRITTAS BAY PARK',
'JACK WHITES PUB',
'GERMAINES BALTINGLASS PRIVATE SUPPLY',
'RATHSALLAGH HOUSE PRIVATE SUPPLY',
'CULLENS SHOP BRITTAS BAY PRIVATE WATER SUPPLY',
'GLEN OF THE DOWNS GOLF CLUB',
'RITZ CARLTON HOTEL',
'KILRUDDERY HOUSE',
'DJOUCE GOLD CLUB',
'BROOKLODGE HOTEL',
'ROUNDWOOD GOLF CLUB',
'Emyvale Housing Estate',
'Lawless Hotel ',
'Ballyfolan Private Group Water Scheme',
